"""Generate pytest tests from a recorded session.

The input is an asciinema cast v2 file with ``"i"`` (user input),
``"o"`` (app output), and ``"m"`` (marker) events. We:

1. Walk the events in time order.
2. Decode each input chunk into one or more ``RecordedAction``s.
3. Between consecutive inputs, look at the output that arrived and
   pick a short stable text to ``wait_for_text`` on. If nothing
   useful appears, fall back to ``wait_for_stable``.
4. At each marker event, emit a snapshot assertion.
5. Render a complete pytest async test file.
"""

from __future__ import annotations

import enum
import json
import re
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field
from datetime import UTC
from pathlib import Path

from tuiwright._emulator import Emulator
from tuiwright._record.decoders import RecordedAction, decode_input_stream
from tuiwright.screen import Screen

# ---------------------------------------------------------------------------
# Public configuration
# ---------------------------------------------------------------------------


class CodegenStyle(enum.StrEnum):
    """How the generated test should be shaped."""

    COARSE = "coarse"      # collapse runs, named keys, pretty calls (default)
    FAITHFUL = "faithful"  # one call per recorded keystroke
    HYBRID = "hybrid"      # collapse plain text, faithful for keys/mouse


# ---------------------------------------------------------------------------
# Cast event model
# ---------------------------------------------------------------------------


@dataclass
class CastHeader:
    width: int
    height: int
    title: str | None
    env: dict[str, str] = field(default_factory=dict)


@dataclass
class CastEvent:
    time: float
    kind: str   # "i" | "o" | "m"
    data: str   # text payload; we re-encode to bytes when needed


def _parse_cast(path: Path) -> tuple[CastHeader, list[CastEvent]]:
    with path.open("r", encoding="utf-8") as fh:
        first = fh.readline()
        if not first:
            raise ValueError(f"empty cast file: {path}")
        header_raw = json.loads(first)
        header = CastHeader(
            width=int(header_raw.get("width", 80)),
            height=int(header_raw.get("height", 24)),
            title=header_raw.get("title"),
            env=header_raw.get("env", {}),
        )
        events: list[CastEvent] = []
        for line in fh:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            if not isinstance(row, list) or len(row) != 3:
                continue
            events.append(CastEvent(time=float(row[0]), kind=str(row[1]), data=str(row[2])))
    events.sort(key=lambda e: e.time)
    return header, events


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


@dataclass
class _Step:
    """One emitted Python statement (or block) in the generated test body."""

    code: str
    indent: int = 1   # 1 = inside async def


# Code constants
_HEADER_TEMPLATE = '''\
"""Auto-generated by `tuiwright codegen` on {timestamp}.

Source cast: {cast_path}
Command:     {command}

This file is safe to edit — re-running codegen will overwrite it, so
move any hand-tweaks to a different file if you want them preserved.
"""

from __future__ import annotations

import pytest
from syrupy.assertion import SnapshotAssertion

from tuiwright import TuiSession
from tuiwright._snapshot import ScreenSnapshotExtension

pytestmark = pytest.mark.asyncio
'''


def generate_test(
    cast_path: Path | str,
    *,
    command: Sequence[str] | str | None = None,
    test_name: str = "test_recorded",
    style: CodegenStyle = CodegenStyle.COARSE,
    settle_ms: int = 120,
    cols: int | None = None,
    rows: int | None = None,
) -> str:
    """Render the cast at ``cast_path`` into a pytest test file.

    ``command`` overrides the spawn command if you want the test to
    target a different binary than the one recorded. ``cols`` / ``rows``
    likewise override the recorded terminal size.
    """
    cast_path = Path(cast_path)
    header, events = _parse_cast(cast_path)
    spawn_cmd = command or header.title or "REPLACE_ME"
    body_steps = _build_steps(events, header, style=style, settle_ms=settle_ms)

    body = "\n".join(_format_step(s) for s in body_steps)
    use_snapshot = any("snapshot" in s.code for s in body_steps)
    sig_args = "tui: TuiSession, snapshot: SnapshotAssertion" if use_snapshot else "tui: TuiSession"

    out = _HEADER_TEMPLATE.format(
        timestamp=_now_iso(),
        cast_path=cast_path,
        command=_format_command(spawn_cmd),
    )
    cols_arg = cols if cols is not None else header.width
    rows_arg = rows if rows is not None else header.height

    out += (
        f"\n\n"
        f"async def {test_name}({sig_args}) -> None:\n"
        f"    await tui.start({_format_command_arg(spawn_cmd)}, cols={cols_arg}, rows={rows_arg})\n"
        f"{body}\n"
    )
    return out


# ---------------------------------------------------------------------------
# Step assembly
# ---------------------------------------------------------------------------


def _build_steps(
    events: list[CastEvent],
    header: CastHeader,
    *,
    style: CodegenStyle,
    settle_ms: int,
) -> list[_Step]:
    """Walk events, emit input actions + intervening waits + checkpoints."""
    steps: list[_Step] = []
    emulator = Emulator(cols=header.width, rows=header.height)
    output_buffer = bytearray()
    last_screen_text = ""
    first_settle_emitted = False
    snapshot_counter = 0

    # Helper to flush the pending output buffer as a wait_for_*.
    def emit_wait_for(after_chunk: bool) -> None:
        nonlocal last_screen_text, first_settle_emitted
        if not output_buffer:
            return
        emulator.feed(bytes(output_buffer))
        output_buffer.clear()
        current = Screen.from_emulator(emulator).text if emulator.rows else ""
        new_text = _pick_wait_text(last_screen_text, current)
        if new_text:
            steps.append(_Step(f'await tui.wait_for_text({_pyrepr(new_text)})'))
        else:
            steps.append(_Step(f"await tui.wait_for_stable(quiet_ms={settle_ms})"))
        if not first_settle_emitted:
            first_settle_emitted = True
        last_screen_text = current

    for ev in events:
        if ev.kind == "o":
            output_buffer.extend(ev.data.encode("utf-8", "replace"))
            continue

        if ev.kind == "i":
            # Drain any output queued since the last input.
            emit_wait_for(after_chunk=False)
            raw = ev.data.encode("utf-8", "replace")
            actions = decode_input_stream(raw)
            for action in actions:
                steps.append(_Step(_render_action(action, style=style)))
            continue

        if ev.kind == "m":
            # Drain output first so the snapshot reflects the latest state.
            emit_wait_for(after_chunk=True)
            label = ev.data.strip() or f"checkpoint_{snapshot_counter}"
            label = _sanitise_label(label)
            snapshot_counter += 1
            steps.append(_Step(f"await tui.wait_for_stable(quiet_ms={settle_ms})"))
            steps.append(
                _Step(
                    f"assert tui.screen == snapshot("
                    f"extension_class=ScreenSnapshotExtension, name={_pyrepr(label)})"
                )
            )

    # Final drain.
    emit_wait_for(after_chunk=True)
    steps.append(_Step(f"await tui.wait_for_stable(quiet_ms={settle_ms})"))
    return steps


def _render_action(action: RecordedAction, *, style: CodegenStyle) -> str:
    """Render one RecordedAction as a Python statement."""
    if action.kind == "type":
        text = action.data["text"]
        if style == CodegenStyle.FAITHFUL:
            # One press per char (printable).
            calls = []
            for ch in text:
                calls.append(f'await tui.press({_pyrepr(ch)})')
            return "\n".join(calls) if calls else "pass"
        return f'await tui.type({_pyrepr(text)})'
    if action.kind == "press":
        return f'await tui.press({_pyrepr(action.data["key"])})'
    if action.kind == "click":
        row, col = action.data["row"], action.data["col"]
        button = action.data.get("button")
        mods = action.data.get("modifiers")
        args = [f"row={row}", f"col={col}"]
        if button:
            args.append(f"button={_pyrepr(button)}")
        if mods:
            args.append(f"modifiers={tuple(mods)!r}")
        return f"await tui.click({', '.join(args)})"
    if action.kind == "double_click":
        return f'await tui.double_click(row={action.data["row"]}, col={action.data["col"]})'
    if action.kind == "scroll":
        return (
            f'await tui.scroll(row={action.data["row"]}, col={action.data["col"]}, '
            f'direction={_pyrepr(action.data["direction"])}, lines={action.data["lines"]})'
        )
    if action.kind == "drag":
        return (
            f'await tui.drag(from_row={action.data["from_row"]}, '
            f'from_col={action.data["from_col"]}, '
            f'to_row={action.data["to_row"]}, '
            f'to_col={action.data["to_col"]}, '
            f'button={_pyrepr(action.data["button"])})'
        )
    if action.kind == "hover":
        return f'await tui.hover(row={action.data["row"]}, col={action.data["col"]})'
    if action.kind == "paste":
        return f'await tui.paste({_pyrepr(action.data["text"])})'
    if action.kind == "focus":
        return f'await tui.focus(in_={action.data["in_"]})'
    # Unknown: emit a comment so a human can fix.
    raw = action.data.get("bytes", b"")
    return f"# UNKNOWN INPUT: {raw!r}  # consider opening an issue at https://github.com/PandelisZ/tuiwright/issues"


def _format_step(step: _Step) -> str:
    pad = "    " * step.indent
    # Steps with multi-line code (FAITHFUL type splitting) — indent each line.
    lines = step.code.splitlines() or [""]
    return "\n".join(pad + line for line in lines)


# ---------------------------------------------------------------------------
# Wait-text heuristic
# ---------------------------------------------------------------------------


_WAIT_TEXT_MAX_LEN = 40
_WAIT_TEXT_MIN_LEN = 3


def _pick_wait_text(prev: str, current: str) -> str | None:
    """Pick a short stable substring that's new in ``current`` but not ``prev``.

    The heuristic favours human-readable English-like fragments and
    avoids whitespace, lone borders, or noise. Returns None if no good
    candidate exists; caller falls back to ``wait_for_stable``.
    """
    if current == prev:
        return None
    prev_lines = set(prev.split("\n"))
    new_lines = [line.strip() for line in current.split("\n")
                 if line.strip() and line not in prev_lines]
    if not new_lines:
        return None
    # Score candidates by readability: prefer alpha-rich, short-ish text.
    candidates: list[tuple[float, str]] = []
    for line in new_lines:
        for word_run in _word_runs(line):
            wr = word_run.strip()
            if _WAIT_TEXT_MIN_LEN <= len(wr) <= _WAIT_TEXT_MAX_LEN:
                score = sum(1 for c in wr if c.isalnum() or c == " ") / max(1, len(wr))
                candidates.append((score, wr))
    if not candidates:
        return None
    candidates.sort(key=lambda sc: (-sc[0], len(sc[1])))
    return candidates[0][1]


_WORD_RUN_RE: re.Pattern[str] = re.compile(r"[\w][\w \.,:!?'-]{2,}")


def _word_runs(line: str) -> Iterable[str]:
    return _WORD_RUN_RE.findall(line)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _format_command(cmd: str | Sequence[str]) -> str:
    if isinstance(cmd, str):
        return cmd
    return " ".join(cmd)


def _format_command_arg(cmd: str | Sequence[str]) -> str:
    if isinstance(cmd, str):
        return _pyrepr(cmd)
    return repr(list(cmd))


_SAFE_LABEL_RE: re.Pattern[str] = re.compile(r"[^a-zA-Z0-9_-]+")


def _sanitise_label(label: str) -> str:
    return _SAFE_LABEL_RE.sub("_", label).strip("_") or "checkpoint"


def _pyrepr(s: str) -> str:
    # Prefer double quotes for friendlier-looking output unless the string
    # itself contains them.
    if '"' not in s and "\n" not in s:
        escaped = s.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return repr(s)


def _now_iso() -> str:
    from datetime import datetime

    return datetime.now(UTC).isoformat(timespec="seconds")
